export const GET_PROJECT = "GET_PROJECT";
export const GET_CATEGORY = "GET_CATEGORY";
export const LOGIN = "LOGIN";
export const REGISTER = "REGISTER";
export const USER_LOGIN = "user_login";

export const POST_EDITOR_CONTENT = "POST_EDITOR_CONTENT";

export const SET_SUBMIT_DRAWER_FUNCTION = "SET_SUBMIT_DRAWER_FUNCTION";
export const SET_SUBMIT_MODAL_FUNCTION = "SET_SUBMIT_MODAL_FUNCTION";

export const GET_PROJECT_DETAIL = "GET_PROJECT_DETAIL";
export const OPEN_FORM = "OPEN_FORM";

export const OPEN_DRAWER = "OPEN_DRAWER";
export const CLOSE_DRAWER = "CLOSE_DRAWER";

export const SHOW_NOTIFICATION = "SHOW_NOTIFICATION";
export const DISPLAY_LOADING = "DISPLAY_LOADING";
export const HIDE_LOADING = "HIDE_LOADING";

export const GET_ALL_USER = "GET_ALL_USER";

export const GET_TASK_STATUS = "GET_TASK_STATUS";

export const OPEN_CREATE_TASK_FORM = "OPEN_CREATE_TASK_FORM";

export const GET_TASK_TYPE = "GET_TASK_TYPE";

export const GET_PRIORITY = "GET_PRIORITY";

export const OPEN_MODAL = "OPEN_MODAL";
export const CLOSE_MODAL = "CLOSE_MODAL";

export const GET_TASK_DETAIL = "GET_TASK_DETAIL";

export const GET_ALL_COMMENT = "GET_ALL_COMMENT";

export const GET_USER_DETAIL = "GET_USER_DETAIL";

export const SET_RESET_FORM_FUNCTION = "SET_RESET_FORM_FUNCTION";
